# Contributing to GitHub repositories

The NHS-R Community welcomes contributions in the form of bug fixes and improvements through issues and code contributions.

## Contributing workflow

If you're new to Github [Github's own contributor's guide](https://github.com/github/docs/blob/main/.github/CONTRIBUTING.md) provides a good overview of these topics.

Start with:

- Review the [issue](#using-issues) list (both open and closed) and raise an issue if this hasn't been raised before or contribute to an existing conversation via the issue.

If you want to continue and make changes to the code then:

- Fork the repository

::: aside
This can be via the GitHub website or [{usethis} package](https://intro-git-github.nhsrcommunity.com/session-fork-clone.html#/title-slide)
:::

- Make changes
- Commit the change(s) and push to your own repository
- Create a new [pull request](#pull-requests-and-merging) 
- You can [link one or many issues the pull request resolves](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) and these will be closed automatically when merged

::: aside
This can be via the GitHub website or use the [{usethis} package](https://intro-git-github.nhsrcommunity.com/session-pull-requests.html#/pushing-to-the-remote-github)
:::

- Wait for pull request to be reviewed and merged
- Celebrate your first step into the open source world and contribute more!

## Contributing any datasets

Particularly for packages like [{NHSRdatasets}](https://github.com/nhs-r-community/NHSRdatasets):

- Add your dataset in the `data` folder, in `.rda` format.  
The best way to do this is with the {usethis} package with "gzip" compression:  `usethis::use_data(data, compress ="gzip")`  

## Contributing guidelines and etiquette {#contrib}

- Previewing any code written locally can help test everything works
- Follow the code of conduct in the repository at all times
- For style guides for text and code refer to the NHS-R Way [Style Guides](https://nhsrway.nhsrcommunity.com/style-guides.html)

:::{.callout-warning collapse=false appearance='default' icon=true}
## Sensitive data (warning)
Never commit or submit anything that is confidential, private or disclose any personal or sensitive data in text or code.

See the chapter [technical guidance - git](#tech-git) on how to avoid and remove sensitive data and history when using git.

For information on how NHS-R Community will respond to any submissions with this data can be found in the [NHS-R Way](https://nhsrway.nhsrcommunity.com/code-of-conduct.html#notice-and-takedown-policy)
:::

When contributing you, as the contributor, certify that you are the original author or have cited the original author(s), are authorised to resuse/reference the material and, if necessary, notified the author(s).
Any content that is found to not be submitted by a rights holder will be dealt with according to the NHS-R Community [Notice and Takedown Policy](https://nhsrway.nhsrcommunity.com/code-of-conduct.html#notice-and-takedown-policy).

## Code of Conduct

When contributing to the NHS-R Community GitHub's the Code of Conduct should be followed and can be found in the repository as `CODE_OF_CONDUCT.md`.
This document can be generated, if missing or it is a new repository by using the {usethis} package and the following code:

```
usethis::use_code_of_conduct(contact = "nhs.rcommunity@nhs.net")
```

## Acknowledgements

This contributing guide is adapted from [NHS Digital's Contributor's Guide](https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/CONTRIBUTING.md).