# NHS-R vision

:::{.callout-warning collapse=false appearance='default' icon=true}
## To be reviewed
The vision was created from a workshop held in 2021 as part of a review of the funding of the community.
:::

## Using R in research

> A mistake in the operating room can threaten the life of one patient; a mistake in statistical analysis or interpretation can lead to hundreds of early deaths. 
So it is perhaps odd that, while we allow a doctor to conduct surgery only after years of training, we give SPSS® (SPSS, Chicago, IL) to almost anyone. 
Moreover, whilst only a surgeon would comment on surgical technique, it seems that anybody, regardless of statistical training, feels confident about commenting on statistical data.

*@vickers_interpreting_2005*

The NHS, as one of the largest hospital and healthcare systems, is a world leader in research. 
Research and evaluation are carried out as funded projects as well as unfunded audits/ evaluation. 
Both of which often require statistics - the analysis often being done in SPSS/ SAS or Excel. 
These methods can produce flawed analyses which, moreover, are not reproducible. 

Many trusts do not employ statistics experts and will only be able to get statistical help on funded work by buying in time from academic/external statisticians. 
This means that the pilot work that clinicians do prior to applying for large grants can often be flawed, or promising work ends up not being completed and the grants never awarded because they didn't have the statistics expertise.

While we would not expect clinicians to become expert coders, the NHS-R community should work to develop and deliver training that would help clinicians to be able to use R, including the development of training specifically for those with a clinical/ non coding background. 
This training needs to include R for statistics as well as the more commonly included data wrangling and visualisation.

Better collaboration between R users working in academia and those in the NHS would also be beneficial.

## Training

The NHS-R Community has developed/is developing training with many of the workshops being made available on the NHS-R Community YouTube channel and course material available on its GitHub (brought together in a [Training book](http://training.nhsrcommunity.com/)). 

## Development 

The NHS-R Community comprises members with a very wide diversity of job roles and skills. 
Although there is no one route to being a skilled and useful analyst/data scientist/R or python developer in health and social care nonetheless the NHS-R Community could usefully contribute to supporting recruitment, training and development of those who use R and other open code approaches to data science and analysis. 

## Appendix A: workshop

The following summarises a workshop about the future of NHS-R Community.

### How has the NHS-R Community contributed to the system thus far?

The positive contribution of the NHS-R Community was shared by all stakeholders and included the following highlights.
For analysts: a safe, trusted, supportive space to learn and share together, a badge of honour, joy, confidence, upskilling, networking, working across organisational boundaries without needing permission. 
For leaders: signposting to a trusted brand and community that can influence policy which is underpinned by two value systems - NHS and open source.
For the wider system: NHS-R Community has shifted thinking on how to secure analytic needs in the future and is perhaps the world’s first open-source community focused on health and care with admirers across the globe.

### What is the need in the system given the change in the health and care landscape?
The system has evolved, and progress has been made since the NHS-R Community was established. 
Still, some common themes persist regarding the needs of the system; skills gaps, infrastructure needs, better collaborative working and more structured peer learning, and the development of analytical leadership. 
Specific examples include: methodological training for analysts, setting professional standards, equipping leaders with analytical thinking skills, supporting the use of operations research methods, building links with social care and researchers, quality assurance processes and more. 
There was consensus that the NHS-R Community should focus on its strengths and not duplicate or drift from this because this may undermine its impact (perhaps because it becomes less relevant to its core members who are flourishing in the freedom of the NHS-R Community).  

### What can the NHS-R Community do to support the system?

The following areas were identified.  

1.	Engage with NHS leaders to help them appreciate the potential of the NHS-R Community as a resource.

2.	Work with NHSD/Transformation Directorate to remove barriers/create resources for IT departments to make open source tools readily available for analysts.

3.	Provide an ‘Ask us’ hub where leaders and analysts can refer their questions or issues so that they can get a "grass roots" view from the NHS-R Community on how these might be best addressed.

::: aside
3. Since the workshop the NHS-R Community has started a "drop in" regular hour once a week.
There also continues to be a friendly and health specific question forum through the NHS-R Community Slack in the #help-with-r channel.

5. A Quarto book [Statement on Tools](https://tools.nhsrcommunity.com/) has been set up to help and support people address tackle these issues. 

6. Considerably change amongst national bodies has occurred since the workshop, nevertheless the NHS-R Community is present at some of the national body meetings in England and Wales.
NHS-R Community is also working closely with the Government Data Science Community and is constantly seeking to connect with colleagues from across the UK and beyond the NHS, for example with Local Authority and Public Health.

7. The Health and Care Analyst Conference (2023) has secured funding for such an event which is closely tied to the NHS-R Community through their both being hosted by The Strategy Unit (part of NHS Midlands & Lancashire Commissioning Support Unit).

7. The GitHub repository [Demos and How tos](https://github.com/nhs-r-community/demos-and-how-tos) is a shared open resource for solutions to common problems.
:::

4.	Scaling local solutions nationally and vice-versa.

5.	Myth busting on "open-source" analytics including addressing security and information governance concerns.

6.	Increased collaboration with national bodies such as NHS Transformation Directorate.

7.	Set up an NHS Data Science Event (say over 3 to 5 days) for the NHS to identify common problems and develop shared solutions.

### We asked a pre-mortem question - imagine the NHS-R Community has died, what led to its demise?

The following were identified.

- The NHS-R Community was too reliant on volunteers who were unable to sustain their input.
- The NHS-R Community lost its values and was no longer a brand that was seen as safe, trusted, welcoming, especially to newbies.
- The NHS-R Community got too pre-occupied with contributing to the centre and so lost touch with grass roots analysts.
- National data science teams/bodies did not feel as if they had a stake in the NHS-R Community and so disengaged with it and could not see its relevance.
- R lost out to Python or some other open data science tool.
- The NHS-R Community did not offer enough "attractors" to analysts (for example wider training, support, development opportunities, and so on).
- The NHS-R Community did not have adequate funds to continue to support it.
- The NHS-R Community  lost its central organising team and so disintegrated.

This should inform our approach to risk over the coming years. 
We should focus on resilience, being forward thinking and responsive, maintaining our values, broadening the organising team, actively seeking & cultivating new members, and finding funding solutions and partners that can support our activities.